- hosts: demo_servers
  vars:
    ansible_connection: ssh
    ansible_host: "{{ lookup('conjur_variable', 'server/' + inventory_hostname + '/host', validate_certs=true) }}"
    ansible_user: "{{ lookup('conjur_variable', 'server/' + inventory_hostname + '/user', validate_certs=true) }}"
    ansible_ssh_pass: "{{ lookup('conjur_variable', 'server/' + inventory_hostname + '/pass', validate_certs=true) }}"

  tasks:
    - name: Get user name
      shell: whoami
      register: theuser

    - name: Get host name
      shell: hostname
      register: thehost

    - debug: msg="I am {{ theuser.stdout }} at {{ thehost.stdout }}"
